# Generated by Django 6.0 on 2025-12-10 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.CharField(max_length=5)),
                ('seat_number', models.CharField(max_length=5)),
                ('is_vip', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.cinemahall')),
            ],
            options={
                'unique_together': {('hall', 'row_number', 'seat_number')},
            },
        ),
    ]
